### ISSUE TITLE
TypeError 2.0.1

### ISSUE THREAD

**Issue by Rorenza** [Steve-xmh/applemusic-like-lyrics#118]
TypeError
Failed to execute 'animate' on 'Element': The provided double value is non-finite.
TypeError: Failed to execute 'animate' on 'Element': The provided double value is non-finite.
    at eval (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:70:42237)
    at A1 (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:24300)
    at eg (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31659)
    at KE (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31511)
    at XH (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31049)
    at t_ (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:40956)
    at ui (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:40314)
    at ng (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:36924)
    at Ca (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:8:3279)
    at t_ (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:41328)

**Comment by Steve-xmh** [comment]
已尝试修复，如问题仍然存在，请告知出错时正在播放的音乐，非常感谢！
