### ISSUE TITLE
Apple Lyrics 崩溃

### ISSUE THREAD

**Issue by PrintlnFu4** [Steve-xmh/applemusic-like-lyrics#119]
仅仅是在后台渲染播放界面十几分钟便崩溃了，下面是崩溃报告:
哦不，出大事情了
发生了不可恢复的错误，给作者送 Issue 吧（
TypeError
Failed to execute 'animate' on 'Element': The provided double value is non-finite.
TypeError: Failed to execute 'animate' on 'Element': The provided double value is non-finite.
    at eval (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:70:42237)
    at A1 (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:24300)
    at eg (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31659)
    at KE (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31511)
    at XH (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:31049)
    at t_ (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:40956)
    at ui (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:40314)
    at ng (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:36924)
    at Ca (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:8:3279)
    at t_ (eval at n (betterncm://betterncm/framework.js:1:22320), <anonymous>:10:41328)

**Comment by Steve-xmh** [comment]
和 #118 撞车
