### ISSUE TITLE
这个我也看不懂

### ISSUE THREAD

**Issue by indulge9451** [Steve-xmh/applemusic-like-lyrics#134]
哦不，出大事情了
发生了不可恢复的错误，给作者送Issue吧（
TypeError
Cannot read property 'state'of null
TypeError:Cannot read property 'state'of null
at eval (eval at n (betterncm://betterncm/framework.js:1:22320),<anonymous>:75:4101)
at A1 (eval at n (betterncm://betterncm/framework.js:1:22320),<anonymous>:10:24300)
at eg (eval at n (betterncm://betterncm/framework.js:1:22320),<anonymous>:10:31659)
at KE (eval at n(betterncm://betterncm/framework.js:1:22320),<anonymous>:10:31511)
at XH(eval at n(betterncm://betterncm/framework.js:1:22320),<anonymous>:10:31049)
at t_(eval at n (betterncm://betterncm/framework.js:1:22320),<anonymous>:10:40956)
at ui (eval at n(betterncm://betterncm/framework.js:1:22320),<anonymous>:10:40314)
at ZE (eval at n (betterncm://betterncm/framework.js:1:22320),<anonymous>:10:35768)
at j4 (eval at n(betterncm://betterncm/framework.js:1:22320),<anonymous>:3:9688)
at L4 (eval at n(betterncm://betterncm/framework.js:1:22320),<anonymous>:3:10082)

**Comment by Steve-xmh** [comment]
现已更新到 2.1.3，因为这个问题我实在不能复现出来，故关闭议题了
