### ISSUE TITLE
TypeError 版本2.0.3

### ISSUE THREAD

**Issue by BrokenScales** [Steve-xmh/applemusic-like-lyrics#140]
TypeError
Cannot read property 'state' of null
TypeError: Cannot read property 'state' of null
    at eval (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:75:4101)
    at A1 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:24300)
    at ag (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31659)
    at JE (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31511)
    at aS (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31049)
    at dS (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:40956)
    at ui (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:40314)
    at e6 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:35768)
    at S4 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:3:9688)
    at I4 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:3:10082)
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/135841333/2f3fde6c-8ba6-4a68-8220-64c8b2a7d37b)
展开后显示:
![image](https://github.com/Steve-xmh/applemusic-like-lyrics/assets/135841333/85542146-61b6-44a2-b578-2d099a0ec4d0)

**Comment by Steve-xmh** [comment]
现已更新到 2.1.3，因为这个问题我实在不能复现出来，故关闭议题了
