### ISSUE TITLE
致命错误

### ISSUE THREAD

**Issue by PIndividual** [Steve-xmh/applemusic-like-lyrics#154]
目前重装，重载和重启网易云均无解，插件彻底无法使用
这是报错信息：
TypeError
p.push is not a function
TypeError: p.push is not a function
    at u (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:1221:223757)
    at eval (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:1221:224415)
    at Nv (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:24300)
    at R8 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31659)
    at Ly (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31511)
    at Aj (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:31049)
    at wj (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:40956)
    at Ds (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:40314)
    at O8 (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:10:36924)
    at kl (eval at n (betterncm://betterncm/framework.js:1:22317), <anonymous>:8:3279)

**Comment by Steve-xmh** [comment]
请提供网易云版本号和对应的插件版本

**Comment by PIndividual** [comment]
网易云2.10.6
BetterNCM 1.2.1
你的插件2.1.5

**Comment by PIndividual** [comment]
如果我还想继续使用插件，我该怎么做？

**Comment by Steve-xmh** [comment]
> 如果我还想继续使用插件，我该怎么做？

可以的话请使用目前 Github 上的最新开发构建，看能不能复现问题，然后将错误信息再提供一下（平时大家使用的都是压缩过的产物所以不是很好回溯问题）
