### ISSUE TITLE
不可恢复的错误

### ISSUE THREAD

**Issue by HaoZi9167** [Steve-xmh/applemusic-like-lyrics#186]
哦不，出大事情了
发生了不可恢复的错误，给作者送 Issue 吧（
如果可以，请尝试使用开发版本复现这个错误，这样子下面的错误信息会更加准确。
TypeError
未知的播放状态值 0
TypeError: 未知的播放状态值 0
    at toPlayState (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:77484:13)
    at eval (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:50086:22)
    at commitHookEffectListMount (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:18856:36)
    at commitLayoutEffectOnFiber (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:18949:23)
    at commitLayoutMountEffects_complete (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:19928:19)
    at commitLayoutEffects_begin (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:19917:17)
    at commitLayoutEffects (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:19868:13)
    at commitRootImpl (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:21301:15)
    at commitRoot (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:21225:15)
    at finishConcurrentRender (eval at n (betterncm://betterncm/framework.js:4:10931), <anonymous>:20753:17)

原因未知...我试着复现

**Comment by HaoZi9167** [comment]
情况是 官方的播放栏歌曲来回跳 从第一首连续跳到最后一首
