### ISSUE TITLE
开发构建错误

### ISSUE THREAD

**Issue by floatanddream** [Steve-xmh/applemusic-like-lyrics#198]
在终端输入yarn后提示
Resolution step
➤ YN0001: │ Error: @applemusic-like-lyrics/lyric@workspace:^: Workspace not found (@applemusic-like-lyrics/lyric@workspace:^)
    at je.getWorkspaceByDescriptor (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:439:3260)
    at cC.getCandidates (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:390:29582)
    at kf.getCandidates (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:391:1264)
    at kf.getCandidates (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:391:1264)
    at E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:439:8033
    at df (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:390:11070)
    at ge (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:439:8013)
    at async Promise.allSettled (index 0)
    at async io (E:\Github\applemusic-like-lyrics\.yarn\releases\yarn-3.6.1.cjs:390:10398)
➤ YN0000: └ Completed in 3s 145ms
➤ YN0000: Failed with errors in 3s 150ms

**Comment by Steve-xmh** [comment]
如果是 3.0 开发分支，需要先行构建 Rust WASM 模块才能初始化仓库
具体可以参考 https://github.com/Steve-xmh/applemusic-like-lyrics/blob/3.0-dev/.github/workflows/build-dev.yaml
