### ISSUE TITLE
在better ncm下载后加载失败

### ISSUE THREAD

**Issue by ltsncm** [Steve-xmh/applemusic-like-lyrics#36]
加载错误记录：Error: 插件脚本 C:\Users\Administrator\betterncm/./plugins_runtime\Apple Music-like lyrics/index.js 加载出错: TypeError: Apple Music-like Lyric 与 RefinedNowPlaying 不兼容，请卸载其中一个插件以继续使用。
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20071), <anonymous>:55:3566)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18476)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at betterncm://betterncm/framework.js:1:21201
    at Array.forEach (<anonymous>)
    at ne (betterncm://betterncm/framework.js:1:21184)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:300
    at betterncm://betterncm/framework.js:1:21281
    at Array.forEach (<anonymous>)
    at ne (betterncm://betterncm/framework.js:1:21184)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:300

**Comment by ningguolin** [comment]
安装说明
你可以前往本仓库的 Release 下载对应的插件包，也可以通过 BetterNCM 的插件商店安装本插件。

请不要将本插件与其它同功能用途的插件混用，作者不会为其做兼容工作！以下是不兼容或有功能影响的插件清单：

[RefinedNowPlaying - 一个美化网易云音乐播放界面的 BetterNCM 插件](https://github.com/solstice23/refined-now-playing-netease)
主题插件作者推荐使用 MoTheme 或 Material You，其它主题插件作者没有使用过，可能需要你做一定的设置调整才能契合主题。

**Comment by ningguolin** [comment]
Apple Music-like Lyric 与 RefinedNowPlaying 不兼容，请卸载其中一个插件以继续使用。
