### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Motive-L** [Steve-xmh/applemusic-like-lyrics#92]
Failed to execute 'animate' on 'Element': The provided double value is non-finite.
TypeError: Failed to execute 'animate' on 'Element': The provided double value is non-finite.
    at eval (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:70:48013)
    at j1 (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:24300)
    at z5 (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:31659)
    at wE (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:31511)
    at kH (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:31049)
    at MH (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:40956)
    at ci (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:40314)
    at C5 (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:36924)
    at La (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:8:3279)
    at MH (eval at n (betterncm://betterncm/framework.js:1:22384), <anonymous>:10:41328)

**Comment by Steve-xmh** [comment]
已修正
